Repository micronaut-projects/micronaut-groovy, pull requests merged in 2020-09, with the labels that each got.

#111 [groovy] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#106 Dependency upgrades
  graphql-gorm/build.gradle
  mongo-gorm/build.gradle
Labels: type: dependency-upgrade

#120 Dependency upgrades
  neo4j-gorm/build.gradle
Labels: type: dependency-upgrade

#123 Dependency upgrades
  gorm-common/build.gradle
  hibernate-gorm/build.gradle
  mongo-gorm/build.gradle
  neo4j-gorm/build.gradle
Labels: type: dependency-upgrade

#125 [groovy] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#126 [groovy] Update common files for branch 2.0.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#127 Bump up micronaut test to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#128 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#129 doc: add Multitenancy gorm section
  src/main/docs/.DS_Store
  src/main/docs/guide/gorm/multitenancyGorm.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs
